config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  devise_for :users
  root to:'home#top'
  get 'home/about' => 'home#about'
  resources:books, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end
  resources:users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  get '/search' => 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: "#{content}")
    elsif method == 'forward'
      Book.where('title LIKE ?', "#{content}%")
    elsif method == 'backward'
      Book.where('title LIKE ?', "%#{content}")
    else
      Book.where('title LIKE ?', "%#{content}%")
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    followed.find_by(following_id: user.id).present?
  end


  validates :name,  uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: "#{content}")
    elsif method == 'forward'
      User.where('name LIKE ?', "#{content}%")
    elsif method == 'backward'
      User.where('name LIKE ?', "%#{content}")
    else
      User.where('name LIKE ?', "%#{content}%")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :introduction, :profile_image_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_user, only:[:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
    flash[:notice] = "You have created book successfully."
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book[:id])
    else
      render :edit
    end
    flash[:notice] = "You have updated book successfully."
  end

  def destroy
    @book.destroy
    redirect_to  books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def ensure_user
    @books = current_user.books
    @book = @books.find_by(id: params[:id])
    redirect_to books_path unless @book
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @book = Book.find_by(id: params[:book_id])
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.book_id = @book.id
    comment.save
    redirect_to book_path(@book.id)
  end

  def destroy
    @book = Book.find_by(id: params[:book_id])
    comment = Comment.find_by(id: params[:id], book_id: params[:book_id])
    comment.destroy
    redirect_to book_path(@book.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find_by(id: params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book.id)
  end

  def destroy
    book = Book.find_by(id: params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    binding.pry
    redirect_to book_path(book.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @content = params[:content]
    @model = params[:model]
    @method = params[:method]
    if @model == 'user'
      @users = User.search_for(@content, @method)
    else
      @books = Book.search_for(@content, @method)
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
    flash[:notice] = "You have updated user successfully."
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_create.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class:"form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class:"btn btn-success" %>
  </div>
<% end %>

app/views/books/_list.html.erb
<h2>Books</h2>
 <table class="table table-hover table-inverse">
  <thead>
   <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>
   <% books.each do |book| %>
   <tr>
     <td>
      <%= link_to (attachment_image_tag book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:'no_image.jpg', size:'30x30'), user_path(book.user) %>
     </td>
     <td>
      <%= link_to book.title, book_path(book.id) %>
     </td>
     <td><%= book.body %></td>
   </tr>
   <% end %>
  </tbody>
 </table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <%= @book.errors.count %> errors prohibited this obj from being saved:<br>
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <%= form_with model:@book, local:true do |f| %>
        <div class="form_group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
        <div class="form_group">
          <label for="book_opinion">Opinion</h4>
          <%= f.text_area :body, class:"form-control book_body" %>
        </div>
        <div class="form_group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:<br>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <%= render 'users/info', user:@user %>
   <%= render 'books/create', book:@book %>
  </div>

  <div class="col-md-8 offset-md-1">
   <%= render 'books/list', books:@books %>
  </div>
 </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model:@book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
 <% if flash[:notice] %>
 <p id="notice">
   <%= flash[:notice] %>
 </p>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user:@user %>
      <%= render 'books/create', book:@new_book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td><%= link_to (attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:'no_image.jpg', size:'30x30'), user_path(@user.id) %><br><%= link_to @user.name, user_path(@user.id) %></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <% if @book.favorited_by?(current_user) %>
            <td><%= link_to book_favorites_path(@book.id), method: :delete do %><i class="fas fa-heart"></i><% end %></td>
          <% else %>
            <td><%= link_to book_favorites_path(@book.id), method: :post do %><i class="far fa-heart"></i><% end %></td>
          <% end %>
          <td>コメント数：<%= @book.comments.count %><td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-danger" %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        </tr>
      </table>

      <table class="comments">
        <% @book.comments.each do |comment| %>
        <tr>
          <td><%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:'no_image.jpg', size:'30x30' %></td>
          <td><%= link_to comment.user.name, user_path(comment.user.id) %></td>
          <td><%= comment.comment %></td>
          <% if comment.user.id = current_user.id %>
            <td><%= link_to '削除', book_comment_path(comment.book.id, comment.id), method: :delete, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
        <% end %>
      </table>

      <div class="new-comment">
        <%= form_with(model: [@book,@comment], local:true) do |f| %>
          <%= f.text_area :comment %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>