config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  devise_for :users
  root to:'home#top'
  get 'home/about' => 'home#about'
  resources:books, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end
  resources:users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  get '/search' => 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: "#{content}")
    elsif method == 'forward'
      Book.where('title LIKE ?', "#{content}%")
    elsif method == 'backward'
      Book.where('title LIKE ?', "%#{content}")
    else
      Book.where('title LIKE ?', "%#{content}%")
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    followed.find_by(following_id: user.id).present?
  end


  validates :name,  uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: "#{content}")
    elsif method == 'forward'
      User.where('name LIKE ?', "#{content}%")
    elsif method == 'backward'
      User.where('name LIKE ?', "%#{content}")
    else
      User.where('name LIKE ?', "%#{content}%")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_user, only:[:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
    flash[:notice] = "You have created book successfully."
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book[:id])
    else
      render :edit
    end
    flash[:notice] = "You have updated book successfully."
  end

  def destroy
    @book.destroy
    redirect_to  books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def ensure_user
    @books = current_user.books
    @book = @books.find_by(id: params[:id])
    redirect_to books_path unless @book
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @book = Book.find_by(id: params[:book_id])
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.book_id = @book.id
    comment.save
    redirect_to book_path(@book.id)
  end

  def destroy
    @book = Book.find_by(id: params[:book_id])
    comment = Comment.find_by(id: params[:id], book_id: params[:book_id])
    comment.destroy
    redirect_to book_path(@book.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find_by(id: params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book.id)
  end

  def destroy
    book = Book.find_by(id: params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    binding.pry
    redirect_to book_path(book.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @content = params[:content]
    @model = params[:model]
    @method = params[:method]
    if @model == 'user'
      @users = User.search_for(@content, @method)
    else
      @books = Book.search_for(@content, @method)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
    flash[:notice] = "You have updated user successfully."
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/_search_form.html.erb
<% if user_signed_in? %>
<div class="container mt-2 mb-2">
  <div class="d-flex text-align-center justify-content-center">
    <%= form_with url: search_path, method: :get, local:true do |f| %>
      <%= f.text_field :content %>
      <%= f.select :model, options_for_select({'User' => 'user', 'Book' => 'book'}) %>
      <%= f.select :method, options_for_select({'完全一致' => 'perfect', '前方一致' => 'forward', '後方一致' => 'backward', '部分一致' => 'partial'}) %>
      <%= f.submit 'Search' %>
    <% end %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/76f2c55102.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-10">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <i class="fas fa-home nav-link text-light">Home</i>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
                <i class="fas fa-users nav-link text-light">Users</i>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
                <i class="fas fa-book-open nav-link text-light">Books</i>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt nav-link text-light">logout</i>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path do %>
                <i class="fas fa-home nav-link text-light">Home</i>
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path do %>
                <i class="fas fa-link nav-link text-light">About</i>
                <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus nav-link text-light">sign up</i>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <i class="fas fa-sign-in-alt nav-link text-light">login</i>
              <% end %>
            </li>
          <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= render 'layouts/search_form' %>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>